# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param data decompressed data
#' @param level level of compression
#' @export
zstdCompress <- function(data, level) {
    .Call(`_rzstdlib_zstdCompress`, data, level)
}

#' @param data decompressed data
#' @export
zstdDecompress <- function(data) {
    .Call(`_rzstdlib_zstdDecompress`, data)
}

